/**:
  ros__parameters:
    verbose: false
    wait_preprocessing: false
    sim_time: 1000.0
    time_step: 0.1
    num_filaments_sec: 7
    variable_rate: false
    filament_stop_steps: 0
    ppm_filament_center: 10.0
    filament_initial_std: 10.0
    filament_growth_gamma: 15.0
    filament_noise_std: 0.02
    gas_type: 13
    temperature: 298.0
    pressure: 1.0
    concentration_unit_choice: 1
    occupancy3D_data: /home/zyc/pmfs_b4_native_validation_20261009/derived_B4/OccupancyGrid3D.csv
    fixed_frame: map
    wind_data: /home/zyc/pmfs_b4_native_validation_20261009/derived_B4/wind
    wind_time_step: 1.0
    allow_looping: false
    loop_from_step: 0
    loop_to_step: 10
    source_position_x: -1.675
    source_position_y: 1.495
    source_position_z: -0.5
    save_results: 1
    results_time_step: 0.5
    results_min_time: 0.0
    results_location: /home/zyc/pmfs_m2_process_observation_20261010/realizations/K2_2/bank
    r6_time_trace_path: /home/zyc/pmfs_m2_process_observation_20261010/realizations/K2_2/PHYSICAL_FRAME_TIME.csv
