"""Independent SCIM-GSL V1 launch; legacy algorithms are untouched."""
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, EmitEvent, TimerAction
from launch.conditions import IfCondition
from launch.events import Shutdown
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution, PythonExpression
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from launch_ros.parameter_descriptions import ParameterValue


def _float(name):
    return ParameterValue(LaunchConfiguration(name), value_type=float)


def _int(name):
    return ParameterValue(LaunchConfiguration(name), value_type=int)


def _bool(name):
    return ParameterValue(LaunchConfiguration(name), value_type=bool)


def generate_launch_description():
    params = PathJoinSubstitution([FindPackageShare("vgr_bridge"), "params", "OPGSL_SCIM_V1.yaml"])
    return LaunchDescription([
        DeclareLaunchArgument("vgr_data_path", default_value=""),
        DeclareLaunchArgument("config_id", default_value="2,4-1_fast"),
        DeclareLaunchArgument("run_id", default_value="opgsl_scim_v1_smoke"),
        DeclareLaunchArgument("algorithm", default_value="OPGSL_SCIM_V1"),
        DeclareLaunchArgument("enable_ncl", default_value="false"),
        DeclareLaunchArgument("raiom_mode", default_value="M0"),
        DeclareLaunchArgument("run_dir", default_value="/tmp/opgsl_scim_v1_smoke"),
        DeclareLaunchArgument("start_x", default_value="0.30"),
        DeclareLaunchArgument("start_y", default_value="-1.20"),
        DeclareLaunchArgument("seed", default_value="0"),
        DeclareLaunchArgument("flight_height", default_value="0.30"),
        DeclareLaunchArgument("realtime_factor", default_value="1.0"),
        DeclareLaunchArgument("timeout_sec", default_value="120.0"),
        DeclareLaunchArgument("sim_stop_at_s", default_value="-1.0"),
        DeclareLaunchArgument("shutdown_sec", default_value="155.0"),
        DeclareLaunchArgument("measurement_settle_samples", default_value="2"),
        DeclareLaunchArgument("measurement_block_samples", default_value="10"),
        DeclareLaunchArgument("params_file", default_value=params),
        DeclareLaunchArgument("cell_size", default_value="1.0"),
        DeclareLaunchArgument("candidate_cap", default_value="64"),
        DeclareLaunchArgument("navigation_timeout_seconds", default_value="6.0"),
        DeclareLaunchArgument("force_first_batch_unreachable", default_value="false"),
        DeclareLaunchArgument("use_transport_model", default_value="true"),
        DeclareLaunchArgument("use_tess", default_value="false"),
        DeclareLaunchArgument("tess_shadow_only", default_value="true"),
        DeclareLaunchArgument("tess_takeover_enabled", default_value="false"),
        DeclareLaunchArgument("tess_profile_estimate_enabled", default_value="false"),
        DeclareLaunchArgument("tess_active_stop", default_value="false"),
        DeclareLaunchArgument("tess_use_qam", default_value="false"),
        DeclareLaunchArgument("tess_adaptive_evidence_gate", default_value="false"),
        DeclareLaunchArgument("tess_loo_validation", default_value="false"),
        DeclareLaunchArgument("tess_performance_aligned_aeg", default_value="false"),
        DeclareLaunchArgument("tess_max_competitors", default_value="4"),
        DeclareLaunchArgument("tess_log_variance_floor", default_value="1e-4"),
        DeclareLaunchArgument("tess_model_discrepancy_variance", default_value="0.05"),
        DeclareLaunchArgument("tess_model_discrepancy_provenance", default_value="FROZEN_V3_PILOT_0P05"),
        DeclareLaunchArgument("tess_max_navigation_seconds", default_value="20.0"),
        DeclareLaunchArgument("tess_min_corrected_concentration", default_value="1e-6"),
        DeclareLaunchArgument("tess_min_effective_samples", default_value="3"),
        DeclareLaunchArgument("tess_tau_seconds", default_value="1.2"),
        DeclareLaunchArgument("tess_dead_time_seconds", default_value="0.4"),
        DeclareLaunchArgument("tess_p_valid_min", default_value="0.5"),
        DeclareLaunchArgument("tess_warmup_blocks", default_value="8"),
        DeclareLaunchArgument("tess_candidate_nms_radius_m", default_value="1.0"),
        DeclareLaunchArgument("tess_takeover_absolute_margin", default_value="1e-6"),
        DeclareLaunchArgument("tess_takeover_relative_margin", default_value="0.05"),
        DeclareLaunchArgument("tess_duration_slack_seconds", default_value="0.5"),
        DeclareLaunchArgument("tess_profile_prior_power", default_value="0.0"),
        DeclareLaunchArgument("tess_linear_drift", default_value="false"),
        DeclareLaunchArgument("tess_background_concentration", default_value="0.0"),
        DeclareLaunchArgument("tess_scenario_log_wind_step", default_value="0.10"),
        DeclareLaunchArgument("tess_scenario_log_diffusion_step", default_value="0.10"),
        DeclareLaunchArgument("transport_graph_spacing_cells", default_value="5"),
        DeclareLaunchArgument("gas_backend", default_value="gaden_player"),
        Node(package="vgr_bridge", executable="vgr_sim_node", name="vgr_uav_sim", output="screen",
             parameters=[{
                 "vgr_data_path": LaunchConfiguration("vgr_data_path"),
                 "config_id": LaunchConfiguration("config_id"),
                 "flight_height": _float("flight_height"),
                 "start_x": _float("start_x"), "start_y": _float("start_y"),
                 "seed": _int("seed"), "allow_vertical_motion": False,
                 "realtime_factor": _float("realtime_factor"),
                 "sensor_model_mode": "fopdt", "gaden_iteration_mode": "seeded_time_replay",
                 "gas_backend": LaunchConfiguration("gas_backend"),
                 "sim_stop_at_s": _float("sim_stop_at_s"),
                 "sensor_trace_file": PathJoinSubstitution([LaunchConfiguration("run_dir"), "raw_trace.csv"]),
                 "wind_trace_file": PathJoinSubstitution([LaunchConfiguration("run_dir"), "wind_trace.csv"]),
                 "pose_trace_file": PathJoinSubstitution([LaunchConfiguration("run_dir"), "trajectory.csv"]),
                "measurement_trace_file": PathJoinSubstitution([LaunchConfiguration("run_dir"), "measurement_trace.csv"]),
                "continuous_measurement_samples_file": PathJoinSubstitution([LaunchConfiguration("run_dir"), "continuous_measurement_samples.csv"]),
                 "sensor_manifest_file": PathJoinSubstitution([LaunchConfiguration("run_dir"), "sensor_manifest.json"]),
             }]),
        Node(package="vgr_bridge", executable="wind_value_server", name="wind_value_server", output="screen",
             condition=IfCondition(PythonExpression(["'", LaunchConfiguration("gas_backend"), "' == 'legacy_gadentools' "])),
             parameters=[{"vgr_data_path": LaunchConfiguration("vgr_data_path"), "config_id": LaunchConfiguration("config_id")}]),
        Node(package="gmrf_wind_mapping", executable="gmrf_wind_mapping_node", name="gmrf", output="screen",
             parameters=[{"frame_id": "map", "sensor_topic": "/Anemometer/WindSensor_reading", "map_topic": "map",
                          "map_yaml_file": "", "exec_freq": 10.0, "cell_size": 0.3,
                          "verbose": False, "visualize_gmrf": False}]),
        Node(
            package="gsl_server", executable="gsl_actionserver_node", name="gsl_server", output="screen",
            parameters=[LaunchConfiguration("params_file"), {
                # Algorithm wall-time must be the VGR /clock, never launch wall-time.
                "use_sim_time": True,
                "measurement_settle_samples": _int("measurement_settle_samples"),
                "measurement_block_samples": _int("measurement_block_samples"),
                "method": LaunchConfiguration("algorithm"), "maxSearchTime": _float("timeout_sec"),
                "distanceThreshold": -1.0, "useWindGroundTruth": False,
                "run_uuid": LaunchConfiguration("run_id"),
                "resultsFile": PathJoinSubstitution([LaunchConfiguration("run_dir"), "opgsl_scim_v1_result.csv"]),
                "navigationPathFile": PathJoinSubstitution([LaunchConfiguration("run_dir"), "navigation_path.csv"]),
                "source_estimate_trace_file": PathJoinSubstitution([LaunchConfiguration("run_dir"), "source_estimate_trace.csv"]),
                "opgsl.v3.seed": _int("seed"),
                "opgsl.scim.cell_size": _float("cell_size"),
                "opgsl.scim.candidate_cap": _int("candidate_cap"),
                "opgsl.scim.navigation_timeout_seconds": _float("navigation_timeout_seconds"),
                "opgsl.scim.test.force_first_batch_unreachable": _bool("force_first_batch_unreachable"),
                "opgsl.scim.enable_ncl": _bool("enable_ncl"),
                "opgsl.scim.use_transport_model": _bool("use_transport_model"),
                "opgsl.scim.use_tess": _bool("use_tess"),
                "opgsl.scim.tess_shadow_only": _bool("tess_shadow_only"),
                "opgsl.scim.tess_takeover_enabled": _bool("tess_takeover_enabled"),
                "opgsl.scim.tess_profile_estimate_enabled": _bool("tess_profile_estimate_enabled"),
                "opgsl.scim.tess_active_stop": _bool("tess_active_stop"),
                "opgsl.scim.tess_use_qam": _bool("tess_use_qam"),
                "opgsl.scim.tess_adaptive_evidence_gate": _bool("tess_adaptive_evidence_gate"),
                "opgsl.scim.tess_loo_validation": _bool("tess_loo_validation"),
                "opgsl.scim.tess_performance_aligned_aeg": _bool("tess_performance_aligned_aeg"),
                "opgsl.scim.tess_max_competitors": _int("tess_max_competitors"),
                "opgsl.scim.tess_log_variance_floor": _float("tess_log_variance_floor"),
                "opgsl.scim.tess_model_discrepancy_variance": _float("tess_model_discrepancy_variance"),
                "opgsl.scim.tess_model_discrepancy_provenance": LaunchConfiguration("tess_model_discrepancy_provenance"),
                "opgsl.scim.tess_max_navigation_seconds": _float("tess_max_navigation_seconds"),
                "opgsl.scim.tess_min_corrected_concentration": _float("tess_min_corrected_concentration"),
                "opgsl.scim.tess_min_effective_samples": _int("tess_min_effective_samples"),
                "opgsl.scim.tess_tau_seconds": _float("tess_tau_seconds"),
                "opgsl.scim.tess_dead_time_seconds": _float("tess_dead_time_seconds"),
                "opgsl.scim.tess_p_valid_min": _float("tess_p_valid_min"),
                "opgsl.scim.tess_warmup_blocks": _int("tess_warmup_blocks"),
                "opgsl.scim.tess_candidate_nms_radius_m": _float("tess_candidate_nms_radius_m"),
                "opgsl.scim.tess_takeover_absolute_margin": _float("tess_takeover_absolute_margin"),
                "opgsl.scim.tess_takeover_relative_margin": _float("tess_takeover_relative_margin"),
                "opgsl.scim.tess_duration_slack_seconds": _float("tess_duration_slack_seconds"),
                "opgsl.scim.tess_profile_prior_power": _float("tess_profile_prior_power"),
                "opgsl.scim.tess_linear_drift": _bool("tess_linear_drift"),
                "opgsl.scim.tess_background_concentration": _float("tess_background_concentration"),
                "opgsl.scim.tess_scenario_log_wind_step": _float("tess_scenario_log_wind_step"),
                "opgsl.scim.tess_scenario_log_diffusion_step": _float("tess_scenario_log_diffusion_step"),
                "opgsl.scim.transport_graph_spacing_cells": _int("transport_graph_spacing_cells"),
                "raiom.mode": LaunchConfiguration("raiom_mode"),
                "opgsl.v3.trace.evidence": PathJoinSubstitution([LaunchConfiguration("run_dir"), "evidence_trace.csv"]),
                "opgsl.v3.trace.planner": PathJoinSubstitution([LaunchConfiguration("run_dir"), "planner_trace.csv"]),
                "opgsl.v3.trace.stop": PathJoinSubstitution([LaunchConfiguration("run_dir"), "stop_trace.csv"]),
                "opgsl.v3.trace.parameter_snapshot": PathJoinSubstitution([LaunchConfiguration("run_dir"), "resolved_parameters.yaml"]),
                "opgsl.v3.trace.candidate": PathJoinSubstitution([LaunchConfiguration("run_dir"), "candidate_q_trace.csv"]),
                "opgsl.scim.trace.memory": PathJoinSubstitution([LaunchConfiguration("run_dir"), "scim_memory_trace.csv"]),
                "opgsl.scim.trace.contrast": PathJoinSubstitution([LaunchConfiguration("run_dir"), "scim_contrast_trace.csv"]),
                "opgsl.scim.trace.action": PathJoinSubstitution([LaunchConfiguration("run_dir"), "scim_action_trace.csv"]),
                "raiom.trace.action_validity": PathJoinSubstitution([LaunchConfiguration("run_dir"), "action_validity_trace.csv"]),
                "raiom.trace.declaration": PathJoinSubstitution([LaunchConfiguration("run_dir"), "declaration_trace.csv"]),
                "opgsl.scim.tess.trace.blocks": PathJoinSubstitution([LaunchConfiguration("run_dir"), "measurement_blocks.csv"]),
                "opgsl.scim.tess.trace.source": PathJoinSubstitution([LaunchConfiguration("run_dir"), "tess_source_trace.csv"]),
                "opgsl.scim.tess.trace.decision": PathJoinSubstitution([LaunchConfiguration("run_dir"), "tess_decision_trace.csv"]),
                "opgsl.scim.tess.trace.pair": PathJoinSubstitution([LaunchConfiguration("run_dir"), "pair_detail_trace.csv"]),
                "opgsl.scim.tess.trace.region": PathJoinSubstitution([LaunchConfiguration("run_dir"), "tess_region_trace.csv"]),
                "opgsl.scim.tess.trace.reject": PathJoinSubstitution([LaunchConfiguration("run_dir"), "measurement_block_reject_trace.csv"]),
            }]),
        Node(
            package="vgr_bridge", executable="gsl_pilot_runner", name="gsl_pilot_runner", output="screen",
            parameters=[{"algorithm": LaunchConfiguration("algorithm"), "run_id": LaunchConfiguration("run_id"), "run_dir": LaunchConfiguration("run_dir"), "timeout_sec": _float("timeout_sec")}]),
        TimerAction(period=LaunchConfiguration("shutdown_sec"), actions=[EmitEvent(event=Shutdown(reason="normal_budget_end"))]),
    ])
