/**:
  ros__parameters:
    cell_size: 0.1
    models:
    - /home/zyc/pmfs_e3_native_validation_20261009/preprocess_inputs/cad_models/MAPIRlab_tables.stl
    - /home/zyc/pmfs_e3_native_validation_20261009/preprocess_inputs/cad_models/MAPIRlab_walls.stl
    - /home/zyc/pmfs_e3_native_validation_20261009/preprocess_inputs/cad_models/MAPIRlab_wardrobes.stl
    outlets_models:
    - /home/zyc/pmfs_e3_native_validation_20261009/preprocess_inputs/cad_models/MAPIRlab_windows.stl
    - /home/zyc/pmfs_e3_native_validation_20261009/preprocess_inputs/cad_models/MAPIRlab_doors.stl
    empty_point_x: -2.0
    empty_point_y: 2.0
    empty_point_z: 0.3
    floor_height: 0.0
    uniformWind: false
    wind_files: /home/zyc/pmfs_e3_native_validation_20261009/preprocess_inputs/wind/W1/wind_at_cell_centers
    output_path: /home/zyc/pmfs_e3_native_validation_20261009/derived_E3
