cmake_minimum_required(VERSION 3.13)
project(gaden_probe LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(gaden_common REQUIRED)
add_executable(gaden_probe gaden_concentration_probe.cpp)
ament_target_dependencies(gaden_probe rclcpp gaden_common)
target_link_directories(gaden_probe PRIVATE $ENV{GADEN_BSC_LIB})
target_link_options(gaden_probe PRIVATE "-Wl,-rpath-link,$ENV{GADEN_BSC_LIB}")
if(DEFINED ENV{GADEN_SEEDED})
    target_compile_definitions(gaden_probe PRIVATE PF_DEI_SEEDED)
endif()
install(TARGETS gaden_probe DESTINATION bin)
