/**:
  ros__parameters:
    cell_size: 0.1
    models:
    - /home/zyc/pmfs_b4_native_validation_20261009/preprocess_inputs/cad_models/House01-main.stl
    - /home/zyc/pmfs_b4_native_validation_20261009/preprocess_inputs/cad_models/House01Outlet005.stl
    - /home/zyc/pmfs_b4_native_validation_20261009/preprocess_inputs/cad_models/House01Outlet006.stl
    - /home/zyc/pmfs_b4_native_validation_20261009/preprocess_inputs/cad_models/House01Outlet007.stl
    outlets_models:
    - /home/zyc/pmfs_b4_native_validation_20261009/preprocess_inputs/cad_models/House01Outlet001.stl
    - /home/zyc/pmfs_b4_native_validation_20261009/preprocess_inputs/cad_models/House01Outlet002.stl
    - /home/zyc/pmfs_b4_native_validation_20261009/preprocess_inputs/cad_models/House01Outlet003.stl
    - /home/zyc/pmfs_b4_native_validation_20261009/preprocess_inputs/cad_models/House01Outlet004.stl
    empty_point_x: 0.0
    empty_point_y: 0.0
    empty_point_z: 1.0
    floor_height: -0.7
    uniformWind: false
    wind_files: /home/zyc/pmfs_b4_native_validation_20261009/preprocess_inputs/wind/2,4-1_fast/2,4-1_fast
    output_path: /home/zyc/pmfs_b4_native_validation_20261009/derived_B4
