/**:
  ros__parameters:
    verbose: false
    wait_preprocessing: false
    sim_time: 1000.0
    time_step: 0.1
    num_filaments_sec: 10
    variable_rate: false
    filament_stop_steps: 0
    ppm_filament_center: 10.0
    filament_initial_std: 10.0
    filament_growth_gamma: 15.0
    filament_noise_std: 0.02
    gas_type: 10
    temperature: 298.0
    pressure: 1.0
    concentration_unit_choice: 1
    occupancy3D_data: /home/zyc/pmfs_clean_c1_preparation_r6_20261009/derived_C1/OccupancyGrid3D.csv
    fixed_frame: map
    wind_data: /home/zyc/pmfs_clean_c1_preparation_r6_20261009/derived_C1/wind
    wind_time_step: 1.0
    allow_looping: false
    loop_from_step: 0
    loop_to_step: 10
    source_position_x: 0.0
    source_position_y: -1.0
    source_position_z: 0.2
    save_results: 1
    results_time_step: 0.5
    results_min_time: 0.0
    results_location: /home/zyc/pmfs_clean_c1_preparation_r6_20261009/one_realization_C1
    r6_time_trace_path: /home/zyc/pmfs_clean_c1_preparation_r6_20261009/PHYSICAL_FRAME_TIME.csv
