/**:
  ros__parameters:
    projectPath: ""
    sim_time: 30.0
    time_step: 0.1
    wind_time_step: 1.0
    ppm_filament_center: 10.0
    filament_initial_std: 10.0
    filament_growth_gamma: 15.0
    filament_noise_std: 0.01
    num_filaments_sec: 7
    allow_looping: true
    loop_from_step: 1
    loop_to_step: 10
    save_results: 1
    results_time_step: 0.5
    pre_calculate_concentrations: false
    results_location: "/home/zyc/PF_DEI_FORWARD_CLOSURE_20260828/synthetic_native/FilamentSimulation_gasType_10_sourcePosition_-2.00_0.07_0.20"
    gas_type: 10
    source_position_x: -2.0
    source_position_y: 0.07
    source_position_z: 0.2
    occupancy3D_data: "/mnt/hgfs/workspace/GADEN_files/scenarios/House02/OccupancyGrid3D.csv"
    wind_data: "/home/zyc/PF_DEI_FORWARD_CLOSURE_20260828/converted_wind_house02"
    limitRate: false
