/**:
  ros__parameters:
    projectPath: ""
    num_simulators: 1
    initial_iteration: 0
    simulation_data_0: "/home/zyc/PF_DEI_FORWARD_CLOSURE_20260828/synthetic_native/FilamentSimulation_gasType_10_sourcePosition_-2.00_0.07_0.20"
    occupancyFile: "/mnt/hgfs/workspace/GADEN_files/scenarios/House02/OccupancyGrid3D.csv"
    allow_looping: false
    loop_from_iteration: 0
    loop_to_iteration: 57
    player_freq: 1.0
    manual_iteration_mode: true
