/PioneerP3DX/PID:
  ros__parameters:
    fixed_frame: map
    qos_overrides./clock.subscription.depth: 1
    qos_overrides./clock.subscription.durability: volatile
    qos_overrides./clock.subscription.history: keep_last
    qos_overrides./clock.subscription.reliability: best_effort
    qos_overrides./parameter_events.publisher.depth: 1000
    qos_overrides./parameter_events.publisher.durability: volatile
    qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: reliable
    rate: 10.0
    sensor_frame: PioneerP3DX_pid_frame
    sensor_model: 30
    topic: /PioneerP3DX/PID/Sensor_reading
    use_PID_correction_factors: false
    use_sim_time: true
