/basic_sim:
  ros__parameters:
    deltaTime: 0.1
    qos_overrides./parameter_events.publisher.depth: 1000
    qos_overrides./parameter_events.publisher.durability: volatile
    qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: reliable
    speed: 5.0
    use_sim_time: false
    worldFile: /home/zyc/pmfs_b4_official_terminal_namespaced_20261010/overlay/share/pmfs_env/scenarios/B/basicSim/B4.yaml
