/gaden_player:
  ros__parameters:
    allow_looping: false
    gas_display_color_0:
    - 0.0
    - 1.0
    - 0.0
    initial_iteration: 500
    loop_from_iteration: 800
    loop_to_iteration: 900
    num_simulators: 1
    occupancyFile: /home/zyc/pmfs_b4_official_terminal_namespaced_20261010/derived_B4/OccupancyGrid3D.csv
    player_freq: 2.0
    projectPath: ''
    qos_overrides./clock.subscription.depth: 1
    qos_overrides./clock.subscription.durability: volatile
    qos_overrides./clock.subscription.history: keep_last
    qos_overrides./clock.subscription.reliability: best_effort
    qos_overrides./parameter_events.publisher.depth: 1000
    qos_overrides./parameter_events.publisher.durability: volatile
    qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: reliable
    r7_clock_trace_path: /home/zyc/pmfs_b4_official_terminal_namespaced_20261010/runtime/physical_clock_trace.csv
    r7_frame_time_csv: /home/zyc/pmfs_b4_official_terminal_namespaced_20261010/PHYSICAL_FRAME_TIME.csv
    simulation_data_0: /home/zyc/pmfs_b4_official_terminal_namespaced_20261010/one_realization_B4
    use_sim_time: true
