// Native TNQC endpoint evaluator.
//
// This executable is built in the same colcon build as gsl_actionserver_node
// and calls GSL::Utils::ExpectedValue directly. It therefore shares the exact
// PMFS implementation, compiler, standard library and optimization toolchain.
//
// Input CSV is generated by reference/tnqc_vgr_fixed_trajectory_replay.py:
// cell_index,grid_i,grid_j,x,y,source_probability
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <gsl_server/algorithms/Common/Grid2D.hpp>
#include <gsl_server/algorithms/Common/Occupancy.hpp>
#include <gsl_server/algorithms/Common/Utils/Math.hpp>

namespace
{
    std::vector<std::string> splitCsv(const std::string& line)
    {
        std::vector<std::string> out;
        std::stringstream ss(line);
        std::string field;
        while (std::getline(ss, field, ','))
            out.push_back(field);
        return out;
    }
}

int main(int argc, char** argv)
{
    if (argc != 9)
    {
        std::cerr
            << "usage: tnqc_expected_value_native <posterior.csv> "
            << "<grid_width> <grid_height> <cell_size> <origin_x> <origin_y> "
            << "<truth_x> <truth_y>\n";
        return 2;
    }

    const std::string path = argv[1];
    const int width = std::stoi(argv[2]);
    const int height = std::stoi(argv[3]);
    const double cellSize = std::stod(argv[4]);
    const double originX = std::stod(argv[5]);
    const double originY = std::stod(argv[6]);
    const double truthX = std::stod(argv[7]);
    const double truthY = std::stod(argv[8]);

    if (width <= 0 || height <= 0 || !(cellSize > 0.0) ||
        !std::isfinite(cellSize) || !std::isfinite(originX) ||
        !std::isfinite(originY) || !std::isfinite(truthX) ||
        !std::isfinite(truthY))
        throw std::invalid_argument("invalid grid metadata or source truth");

    GSL::Grid2DMetadata metadata;
    metadata.origin = GSL::Vector2(
        static_cast<float>(originX), static_cast<float>(originY));
    metadata.cellSize = static_cast<float>(cellSize);
    metadata.dimensions = GSL::Vector2Int(width, height);
    metadata.scale = 1;
    metadata.numFreeCells = 0;

    const std::size_t totalCells =
        static_cast<std::size_t>(width) * static_cast<std::size_t>(height);
    std::vector<double> probability(totalCells, 0.0);
    std::vector<GSL::Occupancy> occupancy(
        totalCells, GSL::Occupancy::Obstacle);

    std::ifstream file(path);
    if (!file.is_open())
        throw std::runtime_error("cannot open posterior csv: " + path);

    std::string line;
    if (!std::getline(file, line))
        throw std::runtime_error("empty posterior csv");
    if (line != "cell_index,grid_i,grid_j,x,y,source_probability")
        throw std::runtime_error("unexpected posterior csv header: " + line);

    double totalMass = 0.0;
    while (std::getline(file, line))
    {
        if (line.empty())
            continue;
        const auto f = splitCsv(line);
        if (f.size() != 6)
            throw std::runtime_error("malformed posterior csv row: " + line);

        const int gridX = std::stoi(f[1]);
        const int gridY = std::stoi(f[2]);
        const double p = std::stod(f[5]);
        if (gridX < 0 || gridX >= width || gridY < 0 || gridY >= height)
            throw std::runtime_error("posterior grid index out of bounds");
        if (!std::isfinite(p) || p < 0.0)
            throw std::runtime_error("invalid posterior probability");

        const std::size_t index =
            metadata.indexOf(static_cast<std::size_t>(gridX),
                             static_cast<std::size_t>(gridY));
        if (occupancy[index] == GSL::Occupancy::Free)
            throw std::runtime_error("duplicate posterior grid cell");
        occupancy[index] = GSL::Occupancy::Free;
        probability[index] = p;
        ++metadata.numFreeCells;
        totalMass += p;
    }

    if (metadata.numFreeCells == 0 || !(totalMass > 0.0) ||
        !std::isfinite(totalMass))
        throw std::runtime_error("posterior has no valid free-cell mass");

    GSL::Grid2D<double> grid(probability, occupancy, metadata);
    const GSL::Vector2 estimate = GSL::Utils::ExpectedValue(grid, 0.05);
    const double error = std::hypot(
        static_cast<double>(estimate.x) - truthX,
        static_cast<double>(estimate.y) - truthY);

    // The engine identifier is consumed by the replay/aggregate integrity gate.
    std::cout << std::setprecision(17)
              << "{\"engine\":\"gsl_utils_expected_value_linked_native_v1\""
              << ",\"pmfs_top5_x\":" << estimate.x
              << ",\"pmfs_top5_y\":" << estimate.y
              << ",\"pmfs_top5_error_m\":" << error
              << ",\"pmfs_top5_cell_count\":"
              << static_cast<int>(
                     std::ceil(static_cast<double>(metadata.numFreeCells) * 0.05))
              << "}\n";
    return 0;
}
