#include "Fixture.hpp"
#include <omp.h>
namespace GSL::PMFS_internal {void r4_set_gaussian(const std::array<float,2500>&,uint16_t);uint16_t r4_gaussian_index();}
using namespace R4;
class ForwardR5: public Simulations {
public:using Simulations::Simulations;
std::pair<long double,std::vector<float>> replay(const Utils::NQA::Node& n,const fs::path& o,const std::string& id){std::vector<float> m(measuredHitProb.data.size(),0.f);SimulationSource source(&n,measuredHitProb.metadata);simulateSourceInPosition(source,m,true,settings.iterationsToRecord,settings.deltaTime,settings.noiseSTDev);R4Audit::binary(o/(id+"_unblurred.f32"),m);if(settings.blurSigmaX>0||settings.blurSigmaY>0){cv::Mat b(m);b=b.reshape(1,measuredHitProb.metadata.dimensions.y);blurHitMap(b);}return {sourceProbFromMaps(measuredHitProb,m),m};}
};
int main(int argc,char**argv){try{
if(argc!=3)throw std::runtime_error("R5 NATIVE_UPDATE OUTPUT");fs::path n=argv[1],out=argv[2];if(fs::exists(out))throw std::runtime_error("output already exists");fs::create_directories(out/"maps");if(omp_get_max_threads()!=1)throw std::runtime_error("threads != 1");
auto input=csv(n/"input.csv"),meta=csv(n/"metadata.csv");auto& r=meta.at(0);Grid2DMetadata m;m.dimensions={integer(r,"width"),integer(r,"height")};m.origin={float(d(r,"origin_x")),float(d(r,"origin_y"))};m.cellSize=d(r,"cell_size");m.numFreeCells=integer(r,"free_cells");m.scale=25;
size_t count=m.dimensions.x*m.dimensions.y;if(input.size()!=count)throw std::runtime_error("grid shape");std::vector<Occupancy> occ(count);std::vector<HitProbability> hp(count);std::vector<Vector2> wind(count);std::vector<double> posterior(count);std::vector<std::vector<uint8_t>> image(m.dimensions.x,std::vector<uint8_t>(m.dimensions.y));
for(size_t i=0;i<count;i++){occ[i]=integer(input[i],"occupancy")==1?Occupancy::Free:Occupancy::Obstacle;hp[i].logOdds=d(input[i],"logOdds");hp[i].omega=d(input[i],"omega");hp[i].confidence=d(input[i],"confidence");wind[i]={float(d(input[i],"u")),float(d(input[i],"v"))};posterior[i]=d(input[i],"prior_posterior");image[i%m.dimensions.x][i/m.dimensions.x]=occ[i]==Occupancy::Free;}
SimulationSettings settings;settings.maxRegionSize=5;settings.sourceDiscriminationPower=.3;settings.refineFraction=.1;settings.deltaTime=.1;settings.noiseSTDev=.5;settings.iterationsToRecord=300;settings.minWarmupIterations=200;settings.maxWarmupIterations=800;settings.blurSigmaX=1.5;settings.blurSigmaY=1.5;
ForwardR5 sim(Grid2D<HitProbability>(hp,occ,m),Grid2D<double>(posterior,occ,m),Grid2D<Vector2>(wind,occ,m),settings);sim.initializeMap(image);
VisibilityMap visibility(m.dimensions.x,m.dimensions.y,5);auto grid=Grid2D<HitProbability>(hp,occ,m);
for(int x=0;x<m.dimensions.x;x++)for(int y=0;y<m.dimensions.y;y++){Vector2Int ij(x,y);std::vector<Vector2Int> visible;if(grid.freeAt(x,y))for(int j=std::max(0,y-5);j<=std::min(m.dimensions.y-1,y+5);j++)for(int i=std::max(0,x-5);i<=std::min(m.dimensions.x-1,x+5);i++){Vector2Int z(i,j);if(z==ij||GridUtils::PathFree(m,occ,m.indicesToCoordinates(ij),m.indicesToCoordinates(z)))visible.push_back(z);}visibility.emplace(ij,visible);}sim.visibilityMap=&visibility;
std::array<float,2500> cache;std::ifstream c(n/"gaussian_cache.f32",std::ios::binary);c.read(reinterpret_cast<char*>(cache.data()),sizeof(cache));if(!c)throw std::runtime_error("cache read");auto initial=csv(n/"gaussian_initial.csv"),candidates=csv(n/"candidates.csv");std::ofstream scores(out/"candidate_scores.csv");scores<<std::setprecision(21)<<"serial,candidate_id,score,points_used,gaussian_index_after\n";
for(auto& row:candidates){auto id=row.at("candidate_id");size_t np=std::stoul(row.at("point_count"));std::vector<float> pts(np*2);std::ifstream f(n/row.at("points_file"),std::ios::binary);f.read(reinterpret_cast<char*>(pts.data()),pts.size()*sizeof(float));if(!f)throw std::runtime_error("points read");R4Replay::points.clear();for(size_t i=0;i<np;i++)R4Replay::points.emplace_back(pts[2*i],pts[2*i+1]);R4Replay::offset=0;R4Replay::enabled=true;uint16_t index=integer(row,"gaussian_ready_before")?integer(row,"gaussian_index_before"):integer(initial.at(0),"index");r4_set_gaussian(cache,index);Utils::r4_rng_restore(row.at("rng_before"));Utils::NQA::Node leaf(nullptr,{integer(row,"origin_i"),integer(row,"origin_j")},{integer(row,"size_i"),integer(row,"size_j")},image);auto result=sim.replay(leaf,out/"maps",id);if(R4Replay::offset!=np||r4_gaussian_index()!=integer(row,"gaussian_index_after"))throw std::runtime_error("RNG sample consumption mismatch "+id);R4Audit::binary(out/"maps"/(id+".f32"),result.second);scores<<row.at("serial")<<","<<id<<","<<result.first<<","<<np<<","<<r4_gaussian_index()<<"\n";scores.flush();}
std::ofstream(out/"COMPLETE.json")<<"{\"candidate_replays\":"<<candidates.size()<<",\"new_native_goals\":0,\"uses_captured_source_points\":true,\"raw_measurement_map_reconstruction\":false}";
return 0;}catch(std::exception& e){std::cerr<<e.what()<<"\n";return 1;}}
