#!/usr/bin/env python3
"""Qualify one GADEN install overlay for CTPI fast-track build/runtime.

Read-only with respect to the candidate overlay. It validates package structure,
CMake discoverability, ROS package prefix resolution, and ELF dependencies, then
emits a deterministic shell environment only when all checks pass.
"""
from __future__ import annotations
import argparse, hashlib, json, os, subprocess, tempfile
from pathlib import Path

AUTHORIZED_ROOT = Path('/home/zyc/PF_DEI_FORWARD_CLOSURE_20260828/gaden_install')
GADEN_PACKAGES = ('gaden_msgs', 'gaden_common', 'gaden_player')
CUSTOM_PREFIXES = (
    Path('/home/zyc/ros2_ws/install/olfaction_msgs'),
    Path('/home/zyc/ros2_ws/install/gsl_actions'),
    Path('/home/zyc/ros2_ws/install/gmrf_msgs'),
    Path('/home/zyc/ros2_ws/install/gmrf_wind_mapping'),
    Path('/home/zyc/ros2_ws/install/vgr_bridge'),
)
BUILD_REQUIRED_CUSTOM = ('olfaction_msgs', 'gsl_actions', 'gmrf_msgs')


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()


def tree_manifest_hash(root: Path) -> tuple[str, int, int]:
    h = hashlib.sha256(); files = 0; symlinks = 0
    for path in sorted(root.rglob('*'), key=lambda p: p.as_posix()):
        rel = path.relative_to(root).as_posix()
        if path.is_symlink():
            symlinks += 1; payload = f'L\t{rel}\t{os.readlink(path)}\n'.encode()
        elif path.is_file():
            files += 1; payload = f'F\t{rel}\t{sha256_file(path)}\n'.encode()
        elif path.is_dir():
            payload = f'D\t{rel}\n'.encode()
        else:
            payload = f'O\t{rel}\n'.encode()
        h.update(payload)
    return h.hexdigest(), files, symlinks


def cmake_config(prefix: Path, pkg: str) -> Path | None:
    for p in (
        prefix / 'share' / pkg / 'cmake' / f'{pkg}Config.cmake',
        prefix / 'share' / pkg / 'cmake' / f'{pkg.lower()}Config.cmake',
    ):
        if p.is_file(): return p
    return None


def build_env(candidate: Path) -> dict[str, str]:
    env = os.environ.copy()
    prefixes = [candidate/'gaden_player', candidate/'gaden_common', candidate/'gaden_msgs', *CUSTOM_PREFIXES, Path('/opt/ros/humble')]
    prefixes = [p for p in prefixes if p.exists()]
    prefix_text = ':'.join(str(p) for p in prefixes)
    env['CMAKE_PREFIX_PATH'] = prefix_text
    env['AMENT_PREFIX_PATH'] = prefix_text
    libdirs = [p/'lib' for p in prefixes if (p/'lib').is_dir()]
    env['LD_LIBRARY_PATH'] = ':'.join(str(p) for p in libdirs) + ((':' + os.environ.get('LD_LIBRARY_PATH','')) if os.environ.get('LD_LIBRARY_PATH') else '')
    py = []
    for p in prefixes:
        for q in (p/'local/lib/python3.10/dist-packages', p/'lib/python3.10/site-packages'):
            if q.is_dir(): py.append(q)
    for q in (Path('/opt/ros/humble/local/lib/python3.10/dist-packages'), Path('/opt/ros/humble/lib/python3.10/site-packages')):
        if q.is_dir(): py.append(q)
    env['PYTHONPATH'] = ':'.join(str(p) for p in py)
    return env


def write_env_sh(path: Path, env: dict[str, str], candidate: Path) -> None:
    def q(s: str) -> str: return "'" + s.replace("'", "'\"'\"'") + "'"
    path.write_text('\n'.join([
        '# generated by ctpi_vm_dependency_qualifier.py',
        'export CTPI_GADEN_OVERLAY_ROOT=' + q(str(candidate)),
        'export CMAKE_PREFIX_PATH=' + q(env['CMAKE_PREFIX_PATH']),
        'export AMENT_PREFIX_PATH=' + q(env['AMENT_PREFIX_PATH']),
        'export LD_LIBRARY_PATH=' + q(env['LD_LIBRARY_PATH']),
        'export PYTHONPATH=' + q(env['PYTHONPATH']),
        '',
    ]), encoding='utf-8')


def ldd_missing(path: Path) -> list[str]:
    if not path.is_file() or path.is_symlink(): return []
    probe = subprocess.run(['file','-b',str(path)], capture_output=True, text=True)
    if 'ELF' not in probe.stdout: return []
    proc = subprocess.run(['ldd',str(path)], capture_output=True, text=True)
    return [x.strip() for x in (proc.stdout + proc.stderr).splitlines() if 'not found' in x]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--candidate-root', type=Path, required=True)
    ap.add_argument('--output', type=Path, required=True)
    ap.add_argument('--env-sh', type=Path, required=True)
    ap.add_argument('--repo-head', default='')
    a = ap.parse_args(); candidate = a.candidate_root.resolve()
    checks: dict[str,bool] = {}; details: dict[str,object] = {}; critical: dict[str,str] = {}
    checks['authorized_exact_root'] = candidate == AUTHORIZED_ROOT
    checks['candidate_root_exists'] = candidate.is_dir()
    checks['candidate_root_not_symlink'] = not a.candidate_root.is_symlink()

    for pkg in GADEN_PACKAGES:
        prefix = candidate/pkg; pkgxml = prefix/'share'/pkg/'package.xml'; setup = prefix/'share'/pkg/'local_setup.bash'; cfg = cmake_config(prefix,pkg)
        checks[f'prefix:{pkg}'] = prefix.is_dir(); checks[f'package_xml:{pkg}'] = pkgxml.is_file(); checks[f'local_setup:{pkg}'] = setup.is_file(); checks[f'cmake_config:{pkg}'] = cfg is not None
        if pkgxml.is_file(): critical[f'{pkg}:package_xml'] = sha256_file(pkgxml)
        if setup.is_file(): critical[f'{pkg}:local_setup'] = sha256_file(setup)
        if cfg: critical[f'{pkg}:cmake_config'] = sha256_file(cfg)

    for pkg in BUILD_REQUIRED_CUSTOM:
        prefix = Path('/home/zyc/ros2_ws/install')/pkg; cfg = cmake_config(prefix,pkg)
        checks[f'custom_cmake_config:{pkg}'] = cfg is not None
        if cfg: critical[f'{pkg}:cmake_config'] = sha256_file(cfg)

    if candidate.is_dir():
        tree_sha,nfiles,nlinks = tree_manifest_hash(candidate); details.update(candidate_tree_sha256=tree_sha,candidate_tree_files=nfiles,candidate_tree_symlinks=nlinks)
    details['critical_sha256'] = critical

    missing: dict[str,list[str]] = {}
    if candidate.is_dir():
        for pkg in GADEN_PACKAGES:
            prefix = candidate/pkg
            if prefix.is_dir():
                for p in prefix.rglob('*'):
                    if p.is_file():
                        bad = ldd_missing(p)
                        if bad: missing[str(p)] = bad
    checks['candidate_elf_dependencies_resolved'] = not missing; details['elf_missing'] = missing

    env = build_env(candidate); details['cmake_prefix_path'] = env.get('CMAKE_PREFIX_PATH',''); details['ament_prefix_path'] = env.get('AMENT_PREFIX_PATH','')
    probe_packages = ('gaden_msgs','rclcpp','rclcpp_action','tf2','tf2_ros','tf2_geometry_msgs','angles','olfaction_msgs','visualization_msgs','geometry_msgs','std_msgs','std_srvs','nav2_msgs','gsl_actions','ament_index_cpp','gmrf_msgs')
    with tempfile.TemporaryDirectory(prefix='ctpi_env_probe_') as td:
        td = Path(td); (td/'CMakeLists.txt').write_text('cmake_minimum_required(VERSION 3.16)\nproject(ctpi_env_probe NONE)\n' + ''.join(f'find_package({p} REQUIRED)\n' for p in probe_packages), encoding='utf-8')
        proc = subprocess.run(['cmake','-S',str(td),'-B',str(td/'build')], env=env, capture_output=True, text=True)
        checks['cmake_dependency_probe'] = proc.returncode == 0; details['cmake_probe_returncode'] = proc.returncode; details['cmake_probe_stdout_tail'] = proc.stdout[-6000:]; details['cmake_probe_stderr_tail'] = proc.stderr[-6000:]

    prefixes = {}; ros2 = Path('/opt/ros/humble/bin/ros2')
    for pkg in GADEN_PACKAGES:
        proc = subprocess.run([str(ros2),'pkg','prefix',pkg], env=env, capture_output=True, text=True); got = proc.stdout.strip(); prefixes[pkg] = {'returncode':proc.returncode,'prefix':got}
        try: under = proc.returncode == 0 and Path(got).resolve().is_relative_to(candidate)
        except Exception: under = False
        checks[f'ros2_prefix_under_candidate:{pkg}'] = under
    details['ros2_prefix'] = prefixes

    passed = all(checks.values()); report = {'contract':'CTPI_M3_FASTTRACK_VM_DEPENDENCY_QUALIFICATION_V1','repo_head':a.repo_head,'candidate_root':str(candidate),'checks':checks,'details':details,'pass':passed,'verdict':'CTPI_VM_DEPENDENCY_QUALIFICATION=PASS' if passed else 'CTPI_VM_DEPENDENCY_QUALIFICATION=FAIL'}
    a.output.parent.mkdir(parents=True, exist_ok=True); a.output.write_text(json.dumps(report,indent=2,sort_keys=True)+'\n',encoding='utf-8')
    if passed:
        a.env_sh.parent.mkdir(parents=True, exist_ok=True); write_env_sh(a.env_sh,env,candidate)
    print(report['verdict'])
    if not passed:
        for k,v in checks.items():
            if not v: print('FAILED='+k)
    return 0 if passed else 2

if __name__ == '__main__': raise SystemExit(main())
